//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Dabis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Dabis.Bank1Soap")]
    public interface Bank1Soap {
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hasBankAccount", ReplyAction="*")]
        WebApplication1.Dabis.hasBankAccountResponse hasBankAccount(WebApplication1.Dabis.hasBankAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hasBankAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.Dabis.hasBankAccountResponse> hasBankAccountAsync(WebApplication1.Dabis.hasBankAccountRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBankAccount", ReplyAction="*")]
        WebApplication1.Dabis.CreateBankAccountResponse CreateBankAccount(WebApplication1.Dabis.CreateBankAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBankAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.Dabis.CreateBankAccountResponse> CreateBankAccountAsync(WebApplication1.Dabis.CreateBankAccountRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CashInAccount", ReplyAction="*")]
        WebApplication1.Dabis.CashInAccountResponse CashInAccount(WebApplication1.Dabis.CashInAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CashInAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.Dabis.CashInAccountResponse> CashInAccountAsync(WebApplication1.Dabis.CashInAccountRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeAccount", ReplyAction="*")]
        WebApplication1.Dabis.ChargeAccountResponse ChargeAccount(WebApplication1.Dabis.ChargeAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.Dabis.ChargeAccountResponse> ChargeAccountAsync(WebApplication1.Dabis.ChargeAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hasBankAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hasBankAccount", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.hasBankAccountRequestBody Body;
        
        public hasBankAccountRequest() {
        }
        
        public hasBankAccountRequest(WebApplication1.Dabis.hasBankAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hasBankAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public hasBankAccountRequestBody() {
        }
        
        public hasBankAccountRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hasBankAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hasBankAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.hasBankAccountResponseBody Body;
        
        public hasBankAccountResponse() {
        }
        
        public hasBankAccountResponse(WebApplication1.Dabis.hasBankAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hasBankAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool hasBankAccountResult;
        
        public hasBankAccountResponseBody() {
        }
        
        public hasBankAccountResponseBody(bool hasBankAccountResult) {
            this.hasBankAccountResult = hasBankAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBankAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBankAccount", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.CreateBankAccountRequestBody Body;
        
        public CreateBankAccountRequest() {
        }
        
        public CreateBankAccountRequest(WebApplication1.Dabis.CreateBankAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBankAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public CreateBankAccountRequestBody() {
        }
        
        public CreateBankAccountRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBankAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBankAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.CreateBankAccountResponseBody Body;
        
        public CreateBankAccountResponse() {
        }
        
        public CreateBankAccountResponse(WebApplication1.Dabis.CreateBankAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBankAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateBankAccountResult;
        
        public CreateBankAccountResponseBody() {
        }
        
        public CreateBankAccountResponseBody(bool CreateBankAccountResult) {
            this.CreateBankAccountResult = CreateBankAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CashInAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CashInAccount", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.CashInAccountRequestBody Body;
        
        public CashInAccountRequest() {
        }
        
        public CashInAccountRequest(WebApplication1.Dabis.CashInAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CashInAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public CashInAccountRequestBody() {
        }
        
        public CashInAccountRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CashInAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CashInAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.CashInAccountResponseBody Body;
        
        public CashInAccountResponse() {
        }
        
        public CashInAccountResponse(WebApplication1.Dabis.CashInAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CashInAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CashInAccountResult;
        
        public CashInAccountResponseBody() {
        }
        
        public CashInAccountResponseBody(double CashInAccountResult) {
            this.CashInAccountResult = CashInAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeAccount", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.ChargeAccountRequestBody Body;
        
        public ChargeAccountRequest() {
        }
        
        public ChargeAccountRequest(WebApplication1.Dabis.ChargeAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double CashToCharge;
        
        public ChargeAccountRequestBody() {
        }
        
        public ChargeAccountRequestBody(string id, double CashToCharge) {
            this.id = id;
            this.CashToCharge = CashToCharge;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.Dabis.ChargeAccountResponseBody Body;
        
        public ChargeAccountResponse() {
        }
        
        public ChargeAccountResponse(WebApplication1.Dabis.ChargeAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChargeAccountResult;
        
        public ChargeAccountResponseBody() {
        }
        
        public ChargeAccountResponseBody(bool ChargeAccountResult) {
            this.ChargeAccountResult = ChargeAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Bank1SoapChannel : WebApplication1.Dabis.Bank1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Bank1SoapClient : System.ServiceModel.ClientBase<WebApplication1.Dabis.Bank1Soap>, WebApplication1.Dabis.Bank1Soap {
        
        public Bank1SoapClient() {
        }
        
        public Bank1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Bank1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Bank1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.Dabis.hasBankAccountResponse WebApplication1.Dabis.Bank1Soap.hasBankAccount(WebApplication1.Dabis.hasBankAccountRequest request) {
            return base.Channel.hasBankAccount(request);
        }
        
        public bool hasBankAccount(string id) {
            WebApplication1.Dabis.hasBankAccountRequest inValue = new WebApplication1.Dabis.hasBankAccountRequest();
            inValue.Body = new WebApplication1.Dabis.hasBankAccountRequestBody();
            inValue.Body.id = id;
            WebApplication1.Dabis.hasBankAccountResponse retVal = ((WebApplication1.Dabis.Bank1Soap)(this)).hasBankAccount(inValue);
            return retVal.Body.hasBankAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.Dabis.hasBankAccountResponse> WebApplication1.Dabis.Bank1Soap.hasBankAccountAsync(WebApplication1.Dabis.hasBankAccountRequest request) {
            return base.Channel.hasBankAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.Dabis.hasBankAccountResponse> hasBankAccountAsync(string id) {
            WebApplication1.Dabis.hasBankAccountRequest inValue = new WebApplication1.Dabis.hasBankAccountRequest();
            inValue.Body = new WebApplication1.Dabis.hasBankAccountRequestBody();
            inValue.Body.id = id;
            return ((WebApplication1.Dabis.Bank1Soap)(this)).hasBankAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.Dabis.CreateBankAccountResponse WebApplication1.Dabis.Bank1Soap.CreateBankAccount(WebApplication1.Dabis.CreateBankAccountRequest request) {
            return base.Channel.CreateBankAccount(request);
        }
        
        public bool CreateBankAccount(string id) {
            WebApplication1.Dabis.CreateBankAccountRequest inValue = new WebApplication1.Dabis.CreateBankAccountRequest();
            inValue.Body = new WebApplication1.Dabis.CreateBankAccountRequestBody();
            inValue.Body.id = id;
            WebApplication1.Dabis.CreateBankAccountResponse retVal = ((WebApplication1.Dabis.Bank1Soap)(this)).CreateBankAccount(inValue);
            return retVal.Body.CreateBankAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.Dabis.CreateBankAccountResponse> WebApplication1.Dabis.Bank1Soap.CreateBankAccountAsync(WebApplication1.Dabis.CreateBankAccountRequest request) {
            return base.Channel.CreateBankAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.Dabis.CreateBankAccountResponse> CreateBankAccountAsync(string id) {
            WebApplication1.Dabis.CreateBankAccountRequest inValue = new WebApplication1.Dabis.CreateBankAccountRequest();
            inValue.Body = new WebApplication1.Dabis.CreateBankAccountRequestBody();
            inValue.Body.id = id;
            return ((WebApplication1.Dabis.Bank1Soap)(this)).CreateBankAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.Dabis.CashInAccountResponse WebApplication1.Dabis.Bank1Soap.CashInAccount(WebApplication1.Dabis.CashInAccountRequest request) {
            return base.Channel.CashInAccount(request);
        }
        
        public double CashInAccount(string id) {
            WebApplication1.Dabis.CashInAccountRequest inValue = new WebApplication1.Dabis.CashInAccountRequest();
            inValue.Body = new WebApplication1.Dabis.CashInAccountRequestBody();
            inValue.Body.id = id;
            WebApplication1.Dabis.CashInAccountResponse retVal = ((WebApplication1.Dabis.Bank1Soap)(this)).CashInAccount(inValue);
            return retVal.Body.CashInAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.Dabis.CashInAccountResponse> WebApplication1.Dabis.Bank1Soap.CashInAccountAsync(WebApplication1.Dabis.CashInAccountRequest request) {
            return base.Channel.CashInAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.Dabis.CashInAccountResponse> CashInAccountAsync(string id) {
            WebApplication1.Dabis.CashInAccountRequest inValue = new WebApplication1.Dabis.CashInAccountRequest();
            inValue.Body = new WebApplication1.Dabis.CashInAccountRequestBody();
            inValue.Body.id = id;
            return ((WebApplication1.Dabis.Bank1Soap)(this)).CashInAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.Dabis.ChargeAccountResponse WebApplication1.Dabis.Bank1Soap.ChargeAccount(WebApplication1.Dabis.ChargeAccountRequest request) {
            return base.Channel.ChargeAccount(request);
        }
        
        public bool ChargeAccount(string id, double CashToCharge) {
            WebApplication1.Dabis.ChargeAccountRequest inValue = new WebApplication1.Dabis.ChargeAccountRequest();
            inValue.Body = new WebApplication1.Dabis.ChargeAccountRequestBody();
            inValue.Body.id = id;
            inValue.Body.CashToCharge = CashToCharge;
            WebApplication1.Dabis.ChargeAccountResponse retVal = ((WebApplication1.Dabis.Bank1Soap)(this)).ChargeAccount(inValue);
            return retVal.Body.ChargeAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.Dabis.ChargeAccountResponse> WebApplication1.Dabis.Bank1Soap.ChargeAccountAsync(WebApplication1.Dabis.ChargeAccountRequest request) {
            return base.Channel.ChargeAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.Dabis.ChargeAccountResponse> ChargeAccountAsync(string id, double CashToCharge) {
            WebApplication1.Dabis.ChargeAccountRequest inValue = new WebApplication1.Dabis.ChargeAccountRequest();
            inValue.Body = new WebApplication1.Dabis.ChargeAccountRequestBody();
            inValue.Body.id = id;
            inValue.Body.CashToCharge = CashToCharge;
            return ((WebApplication1.Dabis.Bank1Soap)(this)).ChargeAccountAsync(inValue);
        }
    }
}
